apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: '12'
    openshift.io/deployment-config.name: whitepaperopenshift
    openshift.io/deployment.name: whitepaperopenshift-12
    openshift.io/scc: anyuid
  creationTimestamp: '2021-02-08T14:29:06Z'
  generateName: whitepaperopenshift-12-
  labels:
    app: whitepaperopenshift
    deployment: whitepaperopenshift-12
    deploymentconfig: whitepaperopenshift
  name: whitepaperopenshift-12-fs685
  namespace: whitepaperopenshift
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: whitepaperopenshift-12
      uid: c1d2acdb-6a19-11eb-bdc3-080027d1760f
  resourceVersion: '565112'
  selfLink: /api/v1/namespaces/whitepaperopenshift/pods/whitepaperopenshift-12-fs685
  uid: fff07c98-6a19-11eb-bdc3-080027d1760f
spec:
  containers:
    - image: >-
        172.30.1.1:5000/whitepaperopenshift/whitepaperopenshift@sha256:bfdb1d1c5f3ae64380649e910327e4025a066f661260675b9c9a7b4706e24eb6
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /index.html
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
      name: whitepaperopenshift
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /index.html
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
      resources:
        limits:
          cpu: 500m
          memory: 2G
        requests:
          cpu: 200m
          memory: 1G
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-fhvlr
          readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: default-dockercfg-bfrcn
  nodeName: localhost
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seLinuxOptions:
      level: 's0:c13,c2'
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
  volumes:
    - name: default-token-fhvlr
      secret:
        defaultMode: 420
        secretName: default-token-fhvlr
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2021-02-08T14:29:06Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2021-03-03T12:52:37Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2021-02-08T14:29:06Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        docker://3a437c6d96b01f12ceb0e4ba36da991253576e7ea5d6d779549cc107aee04810
      image: '172.30.1.1:5000/whitepaperopenshift/whitepaperopenshift:latest'
      imageID: >-
        docker-pullable://172.30.1.1:5000/whitepaperopenshift/whitepaperopenshift@sha256:bfdb1d1c5f3ae64380649e910327e4025a066f661260675b9c9a7b4706e24eb6
      lastState:
        terminated:
          containerID: >-
            docker://5bb9b3c35bfde74ffde966f6b511f4604e6eb7c284801c7d2afe8a3a1f73755b
          exitCode: 143
          finishedAt: '2021-02-13T08:45:23Z'
          reason: Error
          startedAt: '2021-02-13T07:26:40Z'
      name: whitepaperopenshift
      ready: true
      restartCount: 3
      state:
        running:
          startedAt: '2021-03-03T12:52:08Z'
  hostIP: 10.0.2.15
  phase: Running
  podIP: 172.17.0.10
  qosClass: Burstable
  startTime: '2021-02-08T14:29:06Z'
