apiVersion: v1
data:
  DB_PASSWORD: MTIz
  DB_USER: ZGJ1c2Vy
kind: Secret
metadata:
  creationTimestamp: '2021-02-05T08:50:51Z'
  name: whitepaperopenshift-secret
  namespace: whitepaperopenshift
  resourceVersion: '514487'
  selfLink: /api/v1/namespaces/whitepaperopenshift/secrets/whitepaperopenshift-secret
  uid: 3fcd3d2d-678f-11eb-a03e-080027d1760f
type: Opaque
